language: haxe

os:
  - linux

haxe:
  - "4.1.5"
  - development

matrix:
  allow_failures:
    - haxe: development

branches:
  only:
    - master
    - dev

install:
    - haxelib install atom

script:
    - haxe build.hxml
    - curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh

notifications:
  email:
    on_success: never
    on_failure: change
